### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by thingsinjars** [JackHowa/Flooshi#1]
I'd like to use this as the kicking-off point for a project of my own but you haven't specified a license for it. Would you be able to add a LICENSE file? Or not, of course, if you choose not to.

Thanks

**Comment by JackHowa** [comment]
Boom -- just added one. Thanks for asking @thingsinjars https://github.com/JackHowa/Flooshi/commit/f3754af0808199715d1c87761f37cd4a3f229185
